### ISSUE TITLE
issue with the radar and MLAT trajectories

### ISSUE THREAD

**Issue by alex-scp** [hpuhr/ATSDB#46] opened 2018-03-01 00:04 UTC
the trajectories displayed for the radars and MLAT clutter the image because they connect unrelated tracks.

the annexed image shows such a case for radar tracks.

![bug_radar-trajectories-connecting-unrelated-tracks](https://user-images.githubusercontent.com/36778712/36820023-cacec688-1ce3-11e8-840a-06f12cc78c45.png)

**Comment by hpuhr** [comment] 2018-03-01 05:44
This is an issue which stems from the fact that the underlying grouping/line drawing mechanism is too simple at the moment.
Basically, the track_num DBOVariable is used to group the target reports, and everything within a group is connected using lines. Now, when a track_num is re-used in the data, the newer track is also connected to the last one.
I would propose the following:
* Add configurable thresholds in time and position (lat/long/altitude) to not connect the new tracks with lines.
I reflagged the issue, since it is not a bug, but an enhancement for the simple (but working as planned) behaviour.

**Comment by hpuhr** [comment] 2018-03-02 04:02
Agreed. Will be extended later to be able to select a grouping variable (per DBO or for all), with MS TA & Mode A as prominent options.
I would like to keep it that way for some time, since the next step would be a chainer and thats out of scope for now.

**Comment by hpuhr** [comment] 2018-03-03 09:46
Made group lines optional. This should mitigate the issue until a more sophisticated grouping + line connecting mechanism is implemented.

**Comment by hpuhr** [comment] 2020-02-14 06:49
Assumed this was solved by the grouping modes in addition with the connect checkbox.

**Closed by hpuhr** 2020-02-14 06:49 UTC
Labels: enhancement
